### ISSUE TITLE
App hides some errors

### ISSUE THREAD

**Issue by newsiberian** [ctrlplusb/react-async-component#25] opened 2017-04-05 03:30 UTC
Hi,

I'm build a route with with `asyncComponent` and got an unrelated error, but then component wrapped with `asyncComponent`, there is no any errors in browser console, just clean screen. I can catch it only via React dev tool:
![cryptit_155](https://cloud.githubusercontent.com/assets/11130487/24688503/928356ec-19ea-11e7-84f3-0c978625ffd2.png)

but, if I use component without wrapping in `asyncComponent`, then I got an error in browser console, like this:
![cryptit_156](https://cloud.githubusercontent.com/assets/11130487/24688526/b6cdbfa6-19ea-11e7-8162-f569123a29d8.png)

**Comment by kennethtruong** [comment] 2017-04-05 05:06
+1 Yea I also just noticed that my errors were swallowed so we don't know where the error is coming from

**Comment by kennethtruong** [comment] 2017-04-05 05:30
I made a repo of what the issue. I've been using your boilerplate (Love it btw! Appreciate all the work you've been doing).
https://github.com/kennethtruong/react-universally/blob/master/src/shared/components/DemoApp/Home/Home.js#L6 
Usually if the error isn't swallowed by the catch in https://github.com/ctrlplusb/react-async-component/blob/master/src/asyncComponent.js#L134
It would say `Uncaught (in promise) TypeError: Cannot read property 'error' of null` at Line 12 of HomeRoute.js.
But right now it just throws an Error somewhere in the React components rendering stack and it'll be hard to trace where the issue came from. 
I'm not too familiar with the reasoning with catching the error instead of letting it propagate but maybe you can log the error?

**Comment by ctrlplusb** [comment] 2017-04-05 08:09
Sorry chaps, this was a total messup by me. I accidentally commented out the respective logging section. Fix will be released today.

**Comment by kennethtruong** [comment] 2017-04-05 08:23
I did notice that theres a check for node for logging but will your fix account for when SSR is disabled?

**Comment by ctrlplusb** [comment] 2017-04-05 08:39
Yep, already added ` || env === 'browser'`

Thanks for following up :)

**Comment by kennethtruong** [comment] 2017-04-05 08:46
Oh great! Thanks for the quick responses!

**Comment by ctrlplusb** [comment] 2017-04-05 10:40
No problem :)

I have just released a new package.  I also noticed my `react-async-bootstrapper` / `react-tree-walker` were swallowing errors, so I have updated them accordingly too.

**Closed** 2017-04-05 12:09 UTC

**Comment by scf4** [comment] 2017-05-30 21:08
Hey guys, for me it swallows errors with `TypeError: null is not an object (evaluating 'oldNode.parentNode.replaceChild')`. Is this related/expected behaviour or not?
