### ISSUE TITLE
Async component won't hot-reload

### ISSUE THREAD

**Issue by plhosk** [ctrlplusb/react-async-component#14] opened 2017-02-03 20:36 UTC
I moved my app from code-split-component to react-async-component but the Async components don't seem to hot reload properly. When I make a change to an Async component I get the usual messages in Chrome console with no differences ([HMR].. ) however the displayed content doesn't change. If I change an Async component then also change a non-async component, the changes to both appear at the same time.

Relevant section of App.jsx:
```
import { withAsyncComponents } from 'react-async-component'

import store from './store'
import Root from './Root'

function renderApp(Param) {
  const app = (
    <AppContainer>
      <Provider store={store}>
        <Param />
      </Provider>
    </AppContainer>
  )

  withAsyncComponents(app).then(({ appWithAsyncComponents }) =>
    ReactDOM.render(appWithAsyncComponents, rootElement), // eslint-disable-line
  )
}

renderApp(Root)

if (module.hot) {
  module.hot.accept(
    './Root',
    () => renderApp(require('./Root').default), //eslint-disable-line
  )
}
```

AppContent.jsx:
```
import IntroductionAsync from './IntroductionAsync'

<Match pattern="/" exactly component={IntroductionAsync} />
```

IntroductionAsync.jsx:
```
import { createAsyncComponent } from 'react-async-component'

const AsyncIntroduction = createAsyncComponent({
  resolve: () => System.import('./Introduction'),
})

export default AsyncIntroduction
```
The problem occurs when I try to edit Introduction.jsx.

react-async-component@0.2.2
react-hot-loader@3.0.0-beta.6
react-router@4.0.0-alpha.6

Is there something I'm doing wrong or is this a bug of some sort?

**Comment by plhosk** [comment] 2017-02-04 01:07
It started working as expected when I replaced

```
      <Match pattern="/" exactly component={IntroductionAsync} />
```

with the following: 

```
      <Match
        pattern="/"
        exactly
        render={() => {
          const AsyncComponent = createAsyncComponent({
            resolve: () => System.import('./Introduction'),
          })
          return <AsyncComponent />
        }}
      />
```

Any idea why it wasn't working when I had the createAsyncComponent code in IntroductionAsync.jsx?

**Comment by carsonperrotti** [comment] 2017-02-05 20:51
Experiencing the same issue myself.

**Comment by swernerx** [comment] 2017-02-06 06:14
Ooops. The fix would be problematic as it recreates the binding for each render. I don't think that would be a good idea.

**Comment by carsonperrotti** [comment] 2017-02-06 13:20
@swernerx I noticed that as well when I tried it and saw that the component was being lazy loaded again and again. 

@ctrlplusb could this be a bug or an implementation issue?

**Comment by ctrlplusb** [comment] 2017-02-06 14:30
Sorry everyone this is likely a bug - I have been swamped with client work but will be putting through a ton of tests as soon as possible to cover all the expected workflows

**Comment by ctrlplusb** [comment] 2017-02-06 14:35
Yep, agreed with @swernerx - that workaround is not recommended. Your component will always be lazy loaded which could lead to render flashing.

**Comment by plhosk** [comment] 2017-02-06 18:05
Thanks, I edited my comment with a warning.

**Comment by bradbarrow** [comment] 2017-03-01 01:12
Hi folks, I'm experiencing the same.

I'm working in a `react-universally` repo from a month or so ago.

I just updated from code-split-component and left most of the rest of the app alone. I've followed the approach recommended in the README but I have the same issue as above - HMR logs in console with no actual updates.

**Comment by wmertens** [comment] 2017-03-13 19:46
There was an issue with HMR 3 but that has been fixed now https://github.com/gaearon/react-hot-loader/issues/303 - is that what you are seeing?

**Comment by ctrlplusb** [comment] 2017-03-19 00:14
All, I am almost done with `1.0.0-alpha.2`, which includes ___significant___ improvements towards supporting hot reloading, including React Hot Loader.  So far it is working swimmingly, but I need to put it through some of my larger projects to know for sure.

This should land within a few days.

**Comment by GuillaumeCisco** [comment] 2017-03-28 11:28
It works great for me with react-hot-loader and current or alpha version of react-async-component.
I use this piece of code:
```javascript

import 'babel-core/register';
import 'babel-polyfill';

import FastClick from 'fastclick';
import React from 'react';
import {render} from 'react-dom';
import {createRenderer} from 'fela';
import {Provider} from 'react-fela';
import {AsyncComponentProvider} from 'react-async-component';
import injectTapEventPlugin from 'react-tap-event-plugin';
import {AppContainer} from 'react-hot-loader';
import Root from './app/Root/index';
import configureStore from './app/configureStore/index';

const store = configureStore();

FastClick.attach(document.body);
// Needed for onTouchTap
// http://stackoverflow.com/a/34015469/988941
injectTapEventPlugin();

const root = document.getElementById('root');
const renderer = createRenderer();
const mountNode = document.getElementById('stylesheet');
const app = <AsyncComponentProvider>
    <Provider renderer={renderer} mountNode={mountNode}>
        <Root {...{store}} />
    </Provider>
</AsyncComponentProvider>;

const renderHotApp = (RootElement) => {
    render(<AppContainer key={Math.random()}>
        <AsyncComponentProvider>
            <Provider renderer={renderer} mountNode={mountNode}>
                <RootElement {...{store}} />
            </Provider>
        </AsyncComponentProvider>
    </AppContainer>, root);
};


if (process.env.NODE_ENV !== 'production') {
    // whyDidYouUpdate(React, {include: /^Create/});
    // whyDidYouUpdate(React, {exclude: /^AsyncComponent|ListItem|^LogMonitor|^DockMonitor|^FilterMonitor|^JSONNestedNode|^JSONTree|^Overlay|^TouchRipple|^EnhancedButton|^IconButton|^Toolbar|^SvgIcon|^ContentAdd|^Flat|^AutoLock|^Card|^Paper|^ContentClear|^ContentCreate|syncWarnings$|^RaisedButton/});
    if (module.hot) {
        module.hot.accept('./app/Root/index', () =>
            System.import('./app/Root/index').then(module =>
                renderHotApp(module.default),
            ),
        );
    }
    renderHotApp(Root);
}
else {
    render(app, root);
}
```

Note that I use:
```javascript
<AppContainer key={Math.random()}>
```
Otherwise, the async-ed components are not loaded.
I use react-router v4 and react-fela :)

**Comment by ctrlplusb** [comment] 2017-04-03 20:23
Hey all;

React hot loader works with alpha-2 release 🎉

I'll be updating the `next` branch of `react-universally` soon.

**Closed by ctrlplusb** 2017-04-03 20:23 UTC

**Comment by GuillaumeCisco** [comment] 2017-04-07 10:26
Hey @ctrlplusb I've just tested the alpha-2 release, it is the same for my settings.
I still need to put:
```javascript
<AppContainer key={Math.random()}>
```

Is this normal?

**Comment by ctrlplusb** [comment] 2017-04-07 10:29
Hmmm, no that shouldn't be the case, but RHL can be very fidgety to get working, and there are definitely some cases where it won't work at all.  

Take a look at my [starter kit](https://github.com/ctrlplusb/react-universally) for an example of how I set it up.  I have it hot reloading in there pretty well. 👍

**Comment by GuillaumeCisco** [comment] 2017-04-11 15:43
Thank you @ctrlplusb 
I've just looked at your setup and tried to reproduce it but I have the same issue.
I need `module.hot.accept` and `key={Math.random()}`

But I used one of your file which is very clever `ReactHotLoader.js` -> https://github.com/ctrlplusb/react-universally/blob/d71b1e4475b31155260ea7ad3d793890aef5aed4/client/components/ReactHotLoader.js

My new setup is now simplier:
```javascript
/* globals document */

import 'babel-core/register';
import 'babel-polyfill';

import FastClick from 'fastclick';
import React from 'react';
import {render} from 'react-dom';
import {createRenderer} from 'fela';
import {Provider as FelaProvider} from 'react-fela';
import {AsyncComponentProvider, createAsyncContext} from 'react-async-component';
import injectTapEventPlugin from 'react-tap-event-plugin';
import ReactHotLoader from './ReactHotLoader';
import Root from './app/Root/index';
import configureStore from './app/configureStore/index';

const store = configureStore();

FastClick.attach(document.body);
// Needed for onTouchTap
// http://stackoverflow.com/a/34015469/988941
injectTapEventPlugin();

// Create a context for our AsyncComponentProvider.
const asyncComponentsContext = createAsyncContext();

const root = document.getElementById('root');
const renderer = createRenderer();
const mountNode = document.getElementById('stylesheet');

const renderApp = RootElement =>
    <ReactHotLoader key={Math.random()}>
        <AsyncComponentProvider asyncContext={asyncComponentsContext}>
            <FelaProvider renderer={renderer} mountNode={mountNode}>
                <RootElement {...{store}} />
            </FelaProvider>
        </AsyncComponentProvider>
    </ReactHotLoader>;

if (process.env.NODE_ENV !== 'production') {
    if (module.hot) {
        module.hot.accept('./app/Root/index', () =>
            System.import('./app/Root/index').then(module => {
                    const app = renderApp(Root);
                    render(app, root);
                }
            ),
        );
    }
}

const app = renderApp(Root);
render(app, root);
```

My RootElement include the Router because it is deifferent when I'm in dev or prod environment ;)

**Comment by gooddaddy** [comment] 2017-11-12 14:51
"react-async-bootstrapper": "^1.1.2",
    "react-async-component": "^1.0.2",
   "react": "^16.0.0",
    "webpack": "^3.8.1",
    "webpack-dev-middleware": "^1.12.0",
    "webpack-hot-middleware": "^2.20.0",

I still need to put: <AppContainer key={Math.random()}>，
If I do not, it will not work properly, always second times to take effect（如果不这样做，它会不正常工作，总是第二次才生效）。

**Comment by rhyek** [comment] 2017-12-28 22:59
I also need to use `<AppContainer key={Math.random()}>`, but I've noticed reloading works fine without it for components not connected to redux. Connected components only reload for every other change.

**Comment by rhyek** [comment] 2017-12-29 19:24
Fyi, connected components only reloading every other change is no longer an issue with react-hot-loader 4 beta 7.
