### ISSUE TITLE
Infinite Loops are common and easy to occur

### ISSUE THREAD

**Issue by bradennapier** [ctrlplusb/react-async-component#42] opened 2017-05-02 22:27 UTC
If ANY problem happens then I get insanely fast errors going on.  We need some sort of loop detection here to handle this.  Not even sure why it happens - perhaps a way to solve it? Or am I just doing something wrong?

![image](https://cloud.githubusercontent.com/assets/15365418/25641985/d51542ba-2f4b-11e7-9d2c-7b1b850f27cb.png)

**Comment by andylhansen** [comment] 2017-05-11 03:20
I'm also having this problem. Any chance of getting this fixed?

**Comment by ctrlplusb** [comment] 2017-05-11 10:30
Hey @bradennapier and @andylhansen 

Is there any chance you could put together a _minimal_ repo example that reproduces this.  Happy to help from there.

**Comment by bradennapier** [comment] 2017-05-19 21:41
@ctrlplusb - I have had difficulty making it happen on demand.  It seems to randomly occur so there is simply error handling somewhere not being handled and it seems to retry non-stop

![image](https://cloud.githubusercontent.com/assets/15365418/26267894/4d9867c8-3ca1-11e7-9030-7e4826a36bd5.png)

**Comment by mschipperheyn** [comment] 2017-06-13 19:04
Here's a repo where it occurs: https://github.com/mschipperheyn/react-universally/tree/styled-components-762

In this case, it;s related to styled components 2.0.0: https://github.com/styled-components/styled-components/issues/762

**Comment by ctrlplusb** [comment] 2017-06-21 14:09
@mschipperheyn thank you for this valuable diagnosis.  This will be very helpful!

I apologise yet again for my delayed responses.  I have a lot going on at the moment, but will try.  PR's gladly welcome if you reckon you may know the root cause.  It'll likely have to be done against `react-tree-walker`.

**Comment by frankleng** [comment] 2017-06-27 22:53
also ran into this. but hard refresh usually fixes it in my case. tho still not a viable solution to end users.

**Comment by mschipperheyn** [comment] 2017-07-03 12:41
Just had another case. I am using react universally. My website responds to project.com and www.project.com but I had not been entirely consistent in using one or the other. In any case, when I was on project.com everything was fine, but on www.project.com after an initial load, it went into that loop. Perhaps it had something to do with using the canonical meta tag in Helmet. I'm not sure.

**Comment by mschipperheyn** [comment] 2017-07-10 20:01
What are the thoughts on simply using the new import('./SomeComponent).then() syntax?

**Comment by newsiberian** [comment] 2017-07-13 03:46
Hi, in my case I see the following loop. Can't reproduce it in dev environment.
![cryptit_168](https://user-images.githubusercontent.com/11130487/28149527-705e740e-67b8-11e7-8466-1e37aede1049.png)

**Comment by bradennapier** [comment] 2017-07-13 05:12
I mean essentially the issue is that asyncComponent is the one catching the errors.  Any error in the resolution of the component will cause an endless loop.  I actually have been thinking this is more of an issue with webpack and it's retry logic when resolution fails but can't be sure really.

**Comment by xzyfer** [comment] 2017-10-10 02:10
@ctrlplusb I've tracked this down the HRM workaround in [asyncComponent][1]. 

```js
  render() {
      if (
        sharedState.module == null &&
        !this.resolving &&
        typeof window !== 'undefined'
      ) {
        this.resolveModule()
      }


      if (error) {
        return ErrorComponent ? (
          <ErrorComponent {...this.props} error={error} />
        ) : null
      }

      [...]
  }
```


Whenever an error occurs resolving a component `this.state.error = true`, however handling the error happens too late. As a result in an environment where `typeof window !== 'undefined'` i.e. the browser, this results in an infinite `render` loop.

I guess either the error handling needs to be moved above the `this.resolveModule()` call, or the guard around it should take into account the error state.

[1]: https://github.com/ctrlplusb/react-async-component/blob/903ca10c9dadf4869a6555ef0678db0aad21aaa2/src/asyncComponent.js#L183-L195

**Comment by ctrlplusb** [comment] 2017-10-10 08:13
Awesome work @xzyfer! Are you up for creating a PR? Appreciate your time spent looking into this. 👍

**Comment by xzyfer** [comment] 2017-10-10 08:25
Happy to open a PR. I don't grok the semantics of the GAME patch so just
let me know which if the proposed solutions is appropriate.

**Comment by xzyfer** [comment] 2017-10-10 09:24
Opened #60

**Closed** 2017-10-11 07:21 UTC
